=== uss-stargazer/auto-rewards-extension/src/assets/extension.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/uss-stargazer/auto-rewards-extension/src/assets/extension.schema.json",
  "title": "Chrome Extension configuration",
  "description": "A higher level configuration of Chrome's manifest.json for webpack to convert to manifest",
  "type": "object",
  "properties": {
    "baseManifestJson": {
      "description": "Base properties for manifest.json",
      "$ref": "http://json.schemastore.org/chrome-manifest"
    },
    "options": {
      "description": "Path to jsx/tsx file for options page, relative to `src/`",
      "type": "string"
    },
    "sidepanel": {
      "description": "Path to jsx/tsx file for sidepanel page, relative to `src/`",
      "type": "string"
    },
    "background": {
      "description": "Paths to background or service worker scripts, relative to `src/`",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "contentScripts": {
      "description": "Content scripts (with options) to be included in certain pages",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "urlMatches": {
            "description": "URL matches to run content script",
            "type": "array",
            "items": { "type": "string" }
          },
          "scripts": {
            "description": "Content script information",
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "description": "Name of the resulting content script file",
                  "type": "string"
                },
                "path": {
                  "description": "Path to the source content script, relative to `src/`",
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== uss-stargazer/auto-rewards-extension/src/assets/extension.json
{
  "$schema": "./extension.schema.json",
  "baseManifestJson": {
    "manifest_version": 3,
    "name": "AutoRewards",
    "description": "A Chrome extension to automate gathering rewards for a handful of platforms (for example, Microsoft Rewards).",
    "version": "1.0",
    "permissions": ["storage", "sidePanel", "tabs", "cookies", "scripting"],
    "host_permissions": ["<all_urls>"],
    "action": { "default_icon": { "16": "icon.png" } },
    "side_panel": { "default_path": "sidepanel.html" },
    "options_ui": { "page": "options.html", "open_in_tab": true }
  },
  "options": "options.tsx",
  "sidepanel": "sidepanel.tsx",
  "background": ["service-worker.ts", "AARP/service-worker.ts"],
  "contentScripts": [
    {
      "urlMatches": ["<all_urls>"],
      "scripts": [{ "name": "contentScript", "path": "content-script.ts" }]
    },
    {
      "urlMatches": ["https://*.aarp.org/**"],
      "scripts": [
        { "name": "aarpContentScript", "path": "AARP/content-script.ts" }
      ]
    }
  ]
}
